//! Cross-library semantic check: for a handful of named bitmap-IE intents,
//! assert rs-pfcp's own construction produces byte-identical wire output to
//! go-pfcp's, for the same named semantic intent.
//!
//! This is the leg of the interop strategy that a decode-then-re-encode echo
//! test structurally cannot cover: if rs-pfcp's own `unmarshal` and `marshal`
//! are *consistently* wrong in the same way (as `UsageReportTrigger::new` was
//! on the `fix/pfcp-spec-compliance` branch — see docs/analysis/pr-62-flygoat-review.md),
//! an echo round trip is the identity function and passes anyway. Diffing
//! against an independently-generated byte sequence catches that.
//!
//! Each expected byte array below is the full TLV (type+length+value) that
//! `interop/go/cmd/gen-fixtures` produced for that intent using go-pfcp —
//! regenerate with `go run ./cmd/gen-fixtures` from `interop/go/` (it prints
//! ready-to-paste Rust array literals) and see `interop/README.md` for the
//! byte-pattern cross-check notes per intent.

use rs_pfcp::ie::apply_action::ApplyAction;
use rs_pfcp::ie::cp_function_features::CPFunctionFeatures;
use rs_pfcp::ie::report_type::ReportType;
use rs_pfcp::ie::reporting_triggers::ReportingTriggers;
use rs_pfcp::ie::up_function_features::UPFunctionFeatures;
use rs_pfcp::ie::usage_report_trigger::UsageReportTrigger;
use rs_pfcp::ie::Ie;

fn check(name: &str, expected: &[u8], constructed: Ie) {
    let actual = constructed.marshal();
    assert_eq!(
        actual, expected,
        "{name}: rs-pfcp encoding does not match the go-pfcp-generated bytes \
         (expected {expected:02x?}, got {actual:02x?})"
    );
}

#[test]
fn apply_action_forw() {
    check(
        "apply_action_forw",
        &[0x00, 0x2c, 0x00, 0x01, 0x02],
        ApplyAction::from(ApplyAction::FORW).to_ie(),
    );
}

#[test]
fn apply_action_drop_buff() {
    check(
        "apply_action_drop_buff",
        &[0x00, 0x2c, 0x00, 0x01, 0x05],
        (ApplyAction::DROP | ApplyAction::BUFF).to_ie(),
    );
}

#[test]
fn cp_function_features_load() {
    check(
        "cp_function_features_load",
        &[0x00, 0x59, 0x00, 0x01, 0x01],
        CPFunctionFeatures::from(CPFunctionFeatures::LOAD).to_ie(),
    );
}

#[test]
fn cp_function_features_epfar() {
    check(
        "cp_function_features_epfar",
        &[0x00, 0x59, 0x00, 0x01, 0x04],
        CPFunctionFeatures::from(CPFunctionFeatures::EPFAR).to_ie(),
    );
}

#[test]
fn up_function_features_empu() {
    check(
        "up_function_features_empu",
        &[0x00, 0x2b, 0x00, 0x02, 0x00, 0x01],
        UPFunctionFeatures::from(UPFunctionFeatures::EMPU).to_ie(),
    );
}

#[test]
fn up_function_features_pdiu() {
    // FTUP is deliberately not covered here: go-pfcp's UPFunctionFeatures
    // constructor floors its payload at 2 octets for any 1-2 arg call, so it
    // cannot express the 1-octet minimal encoding rs-pfcp produces for a
    // feature confined to octet 5. PDIU (octet 6) is the natural pairing
    // with EMPU where both libraries' minimal encodings coincide.
    check(
        "up_function_features_pdiu",
        &[0x00, 0x2b, 0x00, 0x02, 0x00, 0x02],
        UPFunctionFeatures::from(UPFunctionFeatures::PDIU).to_ie(),
    );
}

#[test]
fn reporting_triggers_periodic() {
    check(
        "reporting_triggers_periodic",
        &[0x00, 0x25, 0x00, 0x02, 0x01, 0x00],
        ReportingTriggers::new().with_periodic(true).to_ie(),
    );
}

#[test]
fn reporting_triggers_linked_urr() {
    check(
        "reporting_triggers_linked_urr",
        &[0x00, 0x25, 0x00, 0x02, 0x80, 0x00],
        ReportingTriggers::new().with_linked_urr(true).to_ie(),
    );
}

#[test]
fn usage_report_trigger_perio() {
    check(
        "usage_report_trigger_perio",
        &[0x00, 0x3f, 0x00, 0x03, 0x01, 0x00, 0x00],
        UsageReportTrigger::from(UsageReportTrigger::PERIO).to_ie(),
    );
}

#[test]
fn usage_report_trigger_volth() {
    check(
        "usage_report_trigger_volth",
        &[0x00, 0x3f, 0x00, 0x03, 0x02, 0x00, 0x00],
        UsageReportTrigger::from(UsageReportTrigger::VOLTH).to_ie(),
    );
}

#[test]
fn report_type_usar() {
    check(
        "report_type_usar",
        &[0x00, 0x27, 0x00, 0x01, 0x02],
        ReportType::usage_report().to_ie(),
    );
}

#[test]
fn report_type_erir() {
    check(
        "report_type_erir",
        &[0x00, 0x27, 0x00, 0x01, 0x04],
        ReportType::error_indication_report().to_ie(),
    );
}
