//! Robustness: every IE parser must return `Err`/`Ok`, never panic, on
//! truncated or flag-permuted input (Phase 2 of the remediation plan).
//!
//! The parser list is generated from the `pub fn unmarshal(&[u8])` entry points
//! in `src/ie/`; `every_ie_module_is_registered` fails if a new IE file is added
//! without being listed here.

use std::panic::{catch_unwind, AssertUnwindSafe};

type Parser = (&'static str, fn(&[u8]));

macro_rules! parsers {
    ($($m:ident :: $t:ident),* $(,)?) => {
        &[$((concat!(stringify!($m), "::", stringify!($t)), |d: &[u8]| {
            let _ = rs_pfcp::ie::$m::$t::unmarshal(d);
        })),*]
    };
}

const PARSERS: &[Parser] = parsers!(
    access_availability_control_information::AccessAvailabilityControlInformation,
    access_availability_information::AccessAvailabilityInformation,
    access_availability_report::AccessAvailabilityReport,
    activate_predefined_rules::ActivatePredefinedRules,
    activation_time::ActivationTime,
    add_mbs_unicast_parameters::AddMbsUnicastParameters,
    additional_monitoring_time::AdditionalMonitoringTime,
    additional_usage_reports_information::AdditionalUsageReportsInformation,
    aggregated_urr_id::AggregatedUrrId,
    aggregated_urrs::AggregatedUrrs,
    alternative_smf_ip_address::AlternativeSmfIpAddress,
    apn_dnn::ApnDnn,
    application_detection_information::ApplicationDetectionInformation,
    application_id::ApplicationId,
    application_ids_pfds::ApplicationIdsPfds,
    application_instance_id::ApplicationInstanceId,
    apply_action::ApplyAction,
    area_session_id::AreaSessionId,
    atsss_control_parameters::AtsssControlParameters,
    atsss_ll_control_information::AtsssLlControlInformation,
    atsss_ll_information::AtsssLlInformation,
    atsss_ll_parameters::AtsssLlParameters,
    average_packet_delay::AveragePacketDelay,
    averaging_window::AveragingWindow,
    bar_id::BarId,
    bridge_management_information_container::BridgeManagementInformationContainer,
    c_tag::CTag,
    called_number::CalledNumber,
    calling_number::CallingNumber,
    cause::Cause,
    clock_drift_control_information::ClockDriftControlInformation,
    clock_drift_report::ClockDriftReport,
    configured_time_domain::ConfiguredTimeDomain,
    cp_function_features::CPFunctionFeatures,
    cp_ip_address::CpIpAddress,
    cp_pfcp_entity_ip_address::CpPfcpEntityIpAddress,
    create_bar::CreateBar,
    create_bridge_info_for_tsc::CreateBridgeInfoForTsc,
    create_far::CreateFar,
    create_mar::CreateMar,
    create_pdr::CreatePdr,
    create_qer::CreateQer,
    create_srr::CreateSrr,
    create_traffic_endpoint::TrafficEndpointId,
    create_urr::CreateUrr,
    created_bridge_info_for_tsc::CreatedBridgeInfoForTsc,
    created_l2tp_session::CreatedL2tpSession,
    created_pdr::CreatedPdr,
    created_traffic_endpoint::CreatedTrafficEndpoint,
    cumulative_rate_ratio_measurement::CumulativeRateRatioMeasurement,
    cumulative_rate_ratio_threshold::CumulativeRateRatioThreshold,
    data_network_access_identifier::DataNetworkAccessIdentifier,
    data_status::DataStatus,
    deactivate_predefined_rules::DeactivatePredefinedRules,
    deactivation_time::DeactivationTime,
    destination_interface::DestinationInterface,
    direct_reporting_information::DirectReportingInformation,
    dl_buffering_duration::DlBufferingDuration,
    dl_buffering_suggested_packet_count::DlBufferingSuggestedPacketCount,
    dl_data_packets_size::DlDataPacketsSize,
    dl_flow_level_marking::DlFlowLevelMarking,
    dl_periodicity::DlPeriodicity,
    dns_query_response_filter::DnsQueryResponseFilter,
    dns_server_address::DnsServerAddress,
    downlink_data_notification_delay::DownlinkDataNotificationDelay,
    downlink_data_report::DownlinkDataReport,
    downlink_data_service_information::DownlinkDataServiceInformation,
    dropped_dl_traffic_threshold::DroppedDlTrafficThreshold,
    dscp_to_ppi_control_information::DscpToPpiControlInformation,
    dscp_to_ppi_mapping_information::DscpToPpiMappingInformation,
    dstt_port_number::DsttPortNumber,
    duplicating_parameters::DuplicatingParameters,
    duration_measurement::DurationMeasurement,
    end_time::EndTime,
    error_indication_report::ErrorIndicationReport,
    ethernet_context_information::EthernetContextInformation,
    ethernet_filter_id::EthernetFilterId,
    ethernet_filter_properties::EthernetFilterProperties,
    ethernet_inactivity_timer::EthernetInactivityTimer,
    ethernet_packet_filter::EthernetPacketFilter,
    ethernet_pdu_session_information::EthernetPduSessionInformation,
    ethernet_traffic_information::EthernetTrafficInformation,
    ethertype::Ethertype,
    event_notification_uri::EventNotificationUri,
    event_quota::EventQuota,
    event_threshold::EventThreshold,
    event_time_stamp::EventTimeStamp,
    extended_dl_buffering_notification_policy::ExtendedDlBufferingNotificationPolicy,
    f_teid::Fteid,
    failed_rule_id::FailedRuleId,
    far_id::FarId,
    flow_information::FlowInformation,
    forwarding_parameters::ForwardingParameters,
    forwarding_policy::ForwardingPolicy,
    fq_csid::FqCsid,
    framed_ipv6_route::FramedIpv6Route,
    framed_route::FramedRoute,
    framed_routing::FramedRouting,
    fseid::Fseid,
    gate_status::GateStatus,
    gbr::Gbr,
    graceful_release_period::GracefulReleasePeriod,
    group_id::GroupId,
    gtpu_path_interface_type::GtpuPathInterfaceType,
    gtpu_path_qos_control_information::GtpuPathQosControlInformation,
    gtpu_path_qos_report::GtpuPathQosReport,
    header_enrichment::HeaderEnrichment,
    hplmn_s_nssai::HplmnSNssai,
    inactivity_detection_time::InactivityDetectionTime,
    ip_address_and_port_number_replacement::IpAddressAndPortNumberReplacement,
    ip_multicast_address::IpMulticastAddress,
    ip_multicast_addressing_info::IpMulticastAddressingInfo,
    ip_version::IpVersion,
    join_ip_multicast_information_within_usage_report::JoinIpMulticastInformationWithinUsageReport,
    l2tp_session_indications::L2tpSessionIndications,
    l2tp_session_information::L2tpSessionInformation,
    l2tp_tunnel_information::L2tpTunnelInformation,
    l2tp_user_authentication::L2tpUserAuthentication,
    leave_ip_multicast_information_within_usage_report::LeaveIpMulticastInformationWithinUsageReport,
    link_specific_multipath_ip_address::LinkSpecificMultipathIpAddress,
    linked_urr_id::LinkedUrrId,
    lns_address::LnsAddress,
    load_control_information::LoadControlInformation,
    local_ingress_tunnel::LocalIngressTunnel,
    mac_address::MacAddress,
    mac_addresses_detected::MacAddressesDetected,
    mac_addresses_removed::MacAddressesRemoved,
    mapped_n6_ip_address::MappedN6IpAddress,
    mar_id::MarId,
    maximum_packet_delay::MaximumPacketDelay,
    maximum_receive_unit::MaximumReceiveUnit,
    mbr::Mbr,
    mbs_multicast_parameters::MbsMulticastParameters,
    mbs_session_identifier::MbsSessionIdentifier,
    mbs_session_n4_control_information::MbsSessionN4ControlInformation,
    mbs_session_n4_information::MbsSessionN4Information,
    mbs_session_n4mb_control_information::MbsSessionN4mbControlInformation,
    mbs_session_n4mb_information::MbsSessionN4mbInformation,
    mbs_unicast_parameters_id::MbsUnicastParametersId,
    mbsn4_resp_flags::Mbsn4RespFlags,
    mbsn4mb_req_flags::Mbsn4mbReqFlags,
    measurement_indication::MeasurementIndication,
    measurement_information::MeasurementInformation,
    measurement_method::MeasurementMethod,
    measurement_period::MeasurementPeriod,
    media_transport_protocol::MediaTransportProtocol,
    metadata::Metadata,
    metric::Metric,
    minimum_packet_delay::MinimumPacketDelay,
    minimum_wait_time::MinimumWaitTime,
    monitoring_time::MonitoringTime,
    mpquic_address_information::MpquicAddressInformation,
    mpquic_control_information::MpquicControlInformation,
    mpquic_parameters::MpquicParameters,
    mptcp_address_information::MptcpAddressInformation,
    mptcp_applicable_indication::MptcpApplicableIndication,
    mptcp_control_information::MptcpControlInformation,
    mptcp_parameters::MptcpParameters,
    mt_sdt_control_information::MtSdtControlInformation,
    mtedt_control_information::MtedtControlInformation,
    multicast_transport_information::MulticastTransportInformation,
    multiplier::Multiplier,
    n6_jitter_measurement::N6JitterMeasurement,
    n6_routing_information::N6RoutingInformation,
    nbns_server_address::NbnsServerAddress,
    network_instance::NetworkInstance,
    nf_instance_id::NfInstanceId,
    node_id::NodeId,
    node_report_type::NodeReportType,
    non_tgpp_access_forwarding_action_information::NonTgppAccessForwardingActionInformation,
    notification_correlation_id::NotificationCorrelationId,
    number_of_reports::NumberOfReports,
    number_of_ue_ip_addresses::NumberOfUeIpAddresses,
    nwtt_port_number::NwttPortNumber,
    oci_flags::OciFlags,
    offending_ie::OffendingIe,
    offending_ie_information::OffendingIeInformation,
    outer_header_creation::OuterHeaderCreation,
    outer_header_removal::OuterHeaderRemoval,
    overload_control_information::OverloadControlInformation,
    packet_delay_thresholds::PacketDelayThresholds,
    packet_rate::PacketRate,
    packet_rate_status::PacketRateStatus,
    packet_rate_status_report::PacketRateStatusReport,
    packet_rate_status_report_within_session_modification_response::PacketRateStatusReportWithinSessionModificationResponse,
    packet_replication_and_detection_carry_on_information::PacketReplicationAndDetectionCarryOnInformation,
    paging_policy_indicator::PagingPolicyIndicator,
    partial_failure_information::PartialFailureInformation,
    path_failure_report::PathFailureReport,
    pdi::Pdi,
    pdn_type::PdnType,
    pdr_id::PdrId,
    peer_up_restart_report::PeerUpRestartReport,
    pfcp_association_release_request::PfcpAssociationReleaseRequest,
    pfcp_session_change_info::PfcpSessionChangeInfo,
    pfcp_session_retention_information::PfcpSessionRetentionInformation,
    pfcpas_req_flags::PfcpasReqFlags,
    pfcpas_rsp_flags::PfcpasRspFlags,
    pfcpau_req_flags::PfcpauReqFlags,
    pfcpsdrsp_flags::PfcpsdrspFlags,
    pfcpse_req_flags::PfcpseReqFlags,
    pfcpsm_req_flags::PfcpsmReqFlags,
    pfcpsr_req_flags::PfcpsrReqFlags,
    pfcpsrrsp_flags::PfcpsrrspFlags,
    pfd_contents::PfdContents,
    pfd_context::PfdContext,
    pmf_address_information::PmfAddressInformation,
    pmf_control_information::PmfControlInformation,
    pmf_parameters::PmfParameters,
    port_management_information_container::PortManagementInformationContainer,
    precedence::Precedence,
    predefined_rules_name::PredefinedRulesName,
    priority::Priority,
    protocol_description::ProtocolDescription,
    provide_atsss_control_information::ProvideAtsssControlInformation,
    provide_rds_configuration_information::ProvideRdsConfigurationInformation,
    proxying::Proxying,
    qer_control_indications::QerControlIndications,
    qer_correlation_id::QerCorrelationId,
    qer_id::QerId,
    qer_indications::QerIndications,
    qfi::Qfi,
    qos_information_in_gtpu_path_qos_report::QosInformationInGtpuPathQosReport,
    qos_monitoring_measurement::QosMonitoringMeasurement,
    qos_monitoring_per_qos_flow_control_information::QosMonitoringPerQosFlowControlInformation,
    qos_monitoring_report::QosMonitoringReport,
    qos_report_trigger::QosReportTrigger,
    query_packet_rate_status_within_session_modification_request::QueryPacketRateStatusWithinSessionModificationRequest,
    query_urr::QueryUrr,
    query_urr_reference::QueryURRReference,
    quota_holding_time::QuotaHoldingTime,
    quota_validity_time::QuotaValidityTime,
    rat_type::RatType,
    rds_configuration_information::RdsConfigurationInformation,
    recovery_time_stamp::RecoveryTimeStamp,
    redirect_information::RedirectInformation,
    redundant_transmission_forwarding_parameters::RedundantTransmissionForwardingParameters,
    redundant_transmission_parameters::RedundantTransmissionParameters,
    remote_gtpu_peer::RemoteGtpuPeer,
    remove_bar::RemoveBar,
    remove_far::RemoveFar,
    remove_mar::RemoveMar,
    remove_mbs_unicast_parameters::RemoveMbsUnicastParameters,
    remove_pdr::RemovePdr,
    remove_qer::RemoveQer,
    remove_srr::RemoveSrr,
    remove_traffic_endpoint::RemoveTrafficEndpoint,
    remove_urr::RemoveUrr,
    report_type::ReportType,
    reporting_control_information::ReportingControlInformation,
    reporting_flags::ReportingFlags,
    reporting_frequency::ReportingFrequency,
    reporting_suggestion_info::ReportingSuggestionInfo,
    reporting_thresholds::ReportingThresholds,
    reporting_triggers::ReportingTriggers,
    requested_access_availability_information::RequestedAccessAvailabilityInformation,
    requested_clock_drift_information::RequestedClockDriftInformation,
    requested_qos_monitoring::RequestedQosMonitoring,
    rqi::Rqi,
    rtp_header_extension_additional_information::RtpHeaderExtensionAdditionalInformation,
    rtp_header_extension_id::RtpHeaderExtensionId,
    rtp_header_extension_information::RtpHeaderExtensionInformation,
    rtp_header_extension_type::RtpHeaderExtensionType,
    rtp_payload_format::RtpPayloadFormat,
    rtp_payload_information::RtpPayloadInformation,
    rtp_payload_type::RtpPayloadType,
    s_tag::STag,
    sdf_filter::SdfFilter,
    sequence_number::SequenceNumber,
    session_report::SessionReport,
    smf_set_id::SmfSetId,
    snssai::Snssai,
    source_interface::SourceInterface,
    source_ip_address::SourceIpAddress,
    srr_id::SrrId,
    start_time::StartTime,
    steering_functionality::SteeringFunctionality,
    steering_mode::SteeringMode,
    steering_mode_indicator::SteeringModeIndicator,
    subsequent_event_quota::SubsequentEventQuota,
    subsequent_event_threshold::SubsequentEventThreshold,
    subsequent_time_quota::SubsequentTimeQuota,
    subsequent_time_threshold::SubsequentTimeThreshold,
    subsequent_volume_quota::SubsequentVolumeQuota,
    subsequent_volume_threshold::SubsequentVolumeThreshold,
    suggested_buffering_packets_count::SuggestedBufferingPacketsCount,
    tgpp_access_forwarding_action_information::TgppAccessForwardingActionInformation,
    three_gpp_interface_type::ThreeGppInterfaceTypeIe,
    thresholds::Thresholds,
    time_of_first_packet::TimeOfFirstPacket,
    time_of_last_packet::TimeOfLastPacket,
    time_offset_measurement::TimeOffsetMeasurement,
    time_offset_threshold::TimeOffsetThreshold,
    time_quota::TimeQuota,
    time_quota_mechanism::TimeQuotaMechanism,
    time_threshold::TimeThreshold,
    timer::Timer,
    tl_container::TlContainer,
    trace_information::TraceInformation,
    traffic_endpoint_id::TrafficEndpointId,
    traffic_parameter_measurement_control_information::TrafficParameterMeasurementControlInformation,
    traffic_parameter_measurement_indication::TrafficParameterMeasurementIndication,
    traffic_parameter_measurement_report::TrafficParameterMeasurementReport,
    traffic_parameter_threshold::TrafficParameterThreshold,
    transport_delay_reporting::TransportDelayReporting,
    transport_level_marking::TransportLevelMarking,
    transport_mode::TransportMode,
    tsc_management_information_within_session_modification_request::TscManagementInformationWithinSessionModificationRequest,
    tsc_management_information_within_session_modification_response::TscManagementInformationWithinSessionModificationResponse,
    tsc_management_information_within_session_report_request::TscManagementInformationWithinSessionReportRequest,
    tsn_bridge_id::TsnBridgeId,
    tsn_time_domain_number::TsnTimeDomainNumber,
    tunnel_password::TunnelPassword,
    tunnel_preference::TunnelPreference,
    ue_ip_address::UeIpAddress,
    ue_ip_address_pool_identity::UeIpAddressPoolIdentity,
    ue_ip_address_pool_information::UeIpAddressPoolInformation,
    ue_ip_address_usage_information::UEIPAddressUsageInformation,
    ue_level_measurements_configuration::UeLevelMeasurementsConfiguration,
    ul_periodicity::UlPeriodicity,
    up_function_features::UPFunctionFeatures,
    update_bar::UpdateBar,
    update_bar_within_session_report_response::UpdateBarWithinSessionReportResponse,
    update_duplicating_parameters::UpdateDuplicatingParameters,
    update_far::UpdateFar,
    update_forwarding_parameters::UpdateForwardingParameters,
    update_mar::UpdateMar,
    update_non_tgpp_access_forwarding_action_information::UpdateNonTgppAccessForwardingActionInformation,
    update_pdr::UpdatePdr,
    update_qer::UpdateQer,
    update_srr::UpdateSrr,
    update_tgpp_access_forwarding_action_information::UpdateTgppAccessForwardingActionInformation,
    update_traffic_endpoint::UpdateTrafficEndpoint,
    update_urr::UpdateUrr,
    updated_pdr::UpdatedPdr,
    ur_seqn::UrSeqn,
    uri::Uri,
    urr_id::UrrId,
    usage_information::UsageInformation,
    usage_report::UsageReport,
    usage_report_sdr::UsageReportSdr,
    usage_report_smr::UsageReportSmr,
    usage_report_srr::UsageReportSrr,
    usage_report_trigger::UsageReportTrigger,
    user_id::UserId,
    user_plane_inactivity_timer::UserPlaneInactivityTimer,
    user_plane_path_failure_report::UserPlanePathFailureReport,
    user_plane_path_recovery_report::UserPlanePathRecoveryReport,
    validity_timer::ValidityTimer,
    vendor_specific_node_report_type::VendorSpecificNodeReportType,
    volume_measurement::VolumeMeasurement,
    volume_quota::VolumeQuota,
    volume_threshold::VolumeThreshold,
    weight::Weight,
);

/// Every octet-length up to this is tried for every input shape.
const MAX_LEN: usize = 40;

#[test]
fn ie_parsers_never_panic_on_truncated_or_flag_permuted_input() {
    let prev = std::panic::take_hook();
    std::panic::set_hook(Box::new(|_| {}));

    let mut failures: Vec<String> = Vec::new();
    for (name, parse) in PARSERS {
        'outer: for first in 0..=255u8 {
            for fill in [0x00u8, 0xFF, 0x5A] {
                for len in 0..=MAX_LEN {
                    let mut buf = vec![fill; len];
                    if let Some(b) = buf.first_mut() {
                        *b = first;
                    }
                    if catch_unwind(AssertUnwindSafe(|| parse(&buf))).is_err() {
                        failures.push(format!("{name}: panic on {buf:02x?}"));
                        break 'outer;
                    }
                }
            }
        }
    }

    std::panic::set_hook(prev);
    assert!(
        failures.is_empty(),
        "{} IE parser(s) panicked:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn every_ie_module_is_registered() {
    let src =
        std::fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/src/ie/mod.rs")).unwrap();
    let registered = include_str!("ie_truncation.rs");
    let missing: Vec<_> = src
        .lines()
        .filter_map(|l| l.strip_prefix("pub mod ")?.strip_suffix(';'))
        .filter(|m| !matches!(*m, "builder_support"))
        .filter(|m| !registered.contains(&format!("    {m}::")))
        .map(str::to_owned)
        .collect();
    assert!(
        missing.is_empty(),
        "IE modules missing from PARSERS: {missing:?}"
    );
}
