name: Bug Report
description: Report a bug in the rs-pfcp library
title: "[BUG] "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out this form to help us understand and reproduce the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create a message with...
        2. Call marshal() on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Actual behavior...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Information Elements (IE)
        - Message Types
        - Message Parsing
        - Binary Encoding/Decoding
        - Examples
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 13, Windows 11]
        - Rust version: [e.g., 1.70.0]
        - rs-pfcp version: [e.g., 0.1.0]
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including stack traces, logs, or packet captures.
      placeholder: Additional context...

  - type: checkboxes
    id: protocol-compliance
    attributes:
      label: Protocol Compliance
      description: Is this related to PFCP protocol compliance?
      options:
        - label: This bug affects 3GPP TS 29.244 compliance
        - label: This bug involves binary message format issues
        - label: This bug affects interoperability with other PFCP implementations