name: Feature Request
description: Request a new feature for the rs-pfcp library
title: "[FEATURE] "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of what you want to happen.
      placeholder: Brief summary of the feature...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: Explain the motivation for this feature...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Information Element (IE)
        - New Message Type
        - Protocol Extension
        - Performance Improvement
        - Developer Experience
        - Documentation
        - Examples/Demos
        - Testing/Quality
        - Other
    validations:
      required: true

  - type: textarea
    id: specification
    attributes:
      label: Detailed Description
      description: |
        Provide a detailed description of the feature. For PFCP protocol features, please reference the relevant section of 3GPP TS 29.244.
      placeholder: |
        Detailed description...
        
        If this is a protocol feature, please include:
        - 3GPP TS 29.244 section reference
        - IE/Message type numbers
        - Binary encoding format
        - Usage scenarios
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternative approaches...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Check all that apply
      options:
        - label: This feature requires new dependencies
        - label: This feature affects the public API
        - label: This feature requires protocol specification changes
        - label: This feature affects binary compatibility
        - label: I'm willing to help implement this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.
      placeholder: Additional context...