[package]
name = "rs-pfcp-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
pcap-file = "2.0"

[dependencies.rs-pfcp]
path = ".."

[[bin]]
name = "unmarshal_message"
path = "fuzz_targets/unmarshal_message.rs"
test = false
doc = false
bench = false

[[bin]]
name = "unmarshal_ie"
path = "fuzz_targets/unmarshal_ie.rs"
test = false
doc = false
bench = false

[[bin]]
name = "describe_lossy"
path = "fuzz_targets/describe_lossy.rs"
test = false
doc = false
bench = false

[[bin]]
name = "seed_corpus"
path = "bin/seed_corpus.rs"
test = false
doc = false
bench = false
